### ISSUE TITLE
Play test

### ISSUE THREAD

**Issue by bradsk88** [bradsk88/Questown#16]

**Comment by 16ar0Wow** [comment]
It won't let me into my modded game when I tried to play it, saying I need 'safe mode' enabled even though loading with that didn't work. Thought I'd tell you about this.
(Though it could be because I'm on a curseforge profile.)

**Comment by 16ar0Wow** [comment]
Nevermind it doesn't work with a minecraft launcher profile, either.

**Comment by bradsk88** [comment]
@16ar0Wow Are you running 1.18.2 and do you have [RoomRecipes](https://modrinth.com/mod/roomrecipes/versions) installed?

Please share your debug logs. But fair warning, this project is very early in development.

**Comment by 16ar0Wow** [comment]
Yes, I'm playing 1.18.2 with RoomRecipes. Here's my debug logs:

18:14:58.324
at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:67) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
18:14:58.324
at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
18:14:58.325
at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
18:14:58.325
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
18:14:58.325
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
18:14:58.325
at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
18:14:58.325
at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
18:14:58.325
at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading}
18:14:58.325
at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
18:14:58.325
at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B}
18:14:58.325
at net.minecraft.client.Minecraft.m_205125_(Minecraft.java:2084) ~[client-1.18.2-20220404.173914-srg.jar%2358!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
18:14:58.325
... 35 more

**Comment by bradsk88** [comment]
@16ar0Wow Hmm. I'm going to need more of that log. Can you please share the entire debug.log file? You can drag and drop it into Github's comment box.

It should be in your `.minecraft/logs` directory.

https://minecrafthopper.net/help/finding-minecraft-data-folder/

**Comment by 16ar0Wow** [comment]
[debug.log](https://github.com/bradsk88/Questown/files/11986605/debug.log)

**Comment by bradsk88** [comment]
@16ar0Wow Ok, looks like I shipped a mis-bundled version of RoomRecipes to Modrinth.

Please let me know if this version works for you.
https://modrinth.com/mod/roomrecipes/version/SQI6u8JX

**Comment by 16ar0Wow** [comment]
It works!

**Comment by bradsk88** [comment]
Nice! I'm actively working on fixing [this fairly major bug](https://github.com/users/bradsk88/projects/13?pane=issue&itemId=31381074), but feel free to poke around with it!
